# Generated by Django 4.2.7 on 2023-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('applicant', 'Applicant')], max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
