# Generated by Django 4.2.7 on 2023-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sss_id', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_license', models.FileField(upload_to='insurance_licenses/')),
                ('investment_certifications', models.FileField(upload_to='investment_certifications/')),
                ('esignature', models.ImageField(upload_to='esignatures/')),
            ],
        ),
    ]
