# Generated by Django 4.2.7 on 2023-12-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ail',
            name='esignature',
        ),
        migrations.RemoveField(
            model_name='ail',
            name='insurance_license',
        ),
        migrations.RemoveField(
            model_name='ail',
            name='investment_certifications',
        ),
    ]
