# Generated by Django 4.2.7 on 2023-12-13 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_ail_esignature_remove_ail_insurance_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('applicant', 'Applicant')], max_length=10)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
