# Generated by Django 4.2.7 on 2023-12-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_mal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_username', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='default_email', max_length=254, null=True)),
                ('comments', models.TextField(blank=True, default='default_comments', null=True)),
            ],
        ),
    ]
